---
title: "About me"
subtitle: "Engineer with proven functional knowledge in applied data science and practical experience deploying AI/ML applications using Streamlit, Flask and Docker. My primary interests are focused on the development and application of real-world solutions using data analysis, machine learning, and artificial intelligence."
about:
  template: solana
  links:
    - icon: github
      text: Github
      href: https://github.com/ramonjgt
    - icon: twitter
      text: Twitter
      href: https://twitter.com
    - icon: envelope
      text: Email
      href: mailto:ramon.gt1997@gmail.com
---

## Education

**Universidad Autónoma de Querétaro** | Querétaro, Querétaro
B.S. in Physics Engineering | Aug 2015 - July 2022

**Universidad Autónoma de Querétaro** | Querétaro, Querétaro
Diploma course in Mathematical Data Science | Feb 2024 - June 2024

## Experience

### Continental | R&D Center, Querétaro

**Data Analyst and Data Scientist** | July 2024 - Present

*   Creation of a Power BI Dashboard to analyze the engineers reported hours. The dashboard makes it easy to recognize trends based on projects milestones and is helpful for making decisions before a workload overload.
*   Developed an NLP-based clustering tool (doc2vec + KNN) to visualize and analyze the complexity of our product based on the number of requirements and them mutual relationship. This would be helpful for detect which cluster owners need to collaborate with each other to be more efficient.
*   Developed a data analysis platform in Python for managing and analyzing IBM JAZZ tickets. This solution featured a robust SQLite schema and a semantic search module leveraging FAISS and Sentence Transformers. Developed and integrated machine learning models for topic clustering, work item recommendations and test cases similarity. Delivered the final platform as an interactive Streamlit application for end-user search and data visualization.
*   Lead Langflow experimentation with LLM models to design and execute RAG pipelines, creating a conversational AI assistant to enhance support for discipline engineers.

**Test Manager** | July 2024 - Present

*   Work with product managers, engineers, and business teams to align testing strategies with projects milestones.
*   Presented insights to leadership using dashboards and reports.
*   Managed project tracking in Agile environments, ensuring timely delivery of test results through sprint planning.

**SW Tester** | Sept 2021 - July 2024

*   Worked with complex data protocols (CAN/UDS), gaining experience in parsing and interpreting structured/unstructured data.
*   Automating repetitive tasks with Python, allowing more focus on high-impact tasks.
*   Test embedded software for automotive braking systems (Ford, Stellantis), ensuring full traceability and milestone alignment via CI/CD pipelines.
*   Collaborated with multidisciplinary teams to translate business requirements into test cases.
*   Debugged and interpreted data logs with SW developers to diagnose issues and applying root-cause analysis.

### UNAM | UMDI, Juriquilla, Querétaro

**Research Stay** | 2017 - 2021

*   Helping Dr. Saúl Iván Hernández Hernández in his investigation. This implied learning about colloids simulations and its physics analysis using parallel paradigms in linux environments.
*   Papers reading for weekly discussions.
*   Sending runs of molecular simulations to the GNU/Linux queuing system.
*   Automating the execution of these runs with the help of scripting in Bash.
*   Analyzing the terabytes of results with the help of Python and its packages Numpy, Pandas and Matplotlib.

## Skills

*   **AI/ML and GenAI**: Scikit-learn, PyTorch, HuggingFace Transformers, Langflow and RAG knowledge.
*   **Programming**: Python and its popular libraries as Numpy, Pandas, Seaborn, Matplotlib and Jupyter Notebooks; Bash, Git, SQL.
*   **DevOps & Deployment**: Docker, Git-based CI/CD, API deployment using Flask and AWS Elastic Beanstalk.
*   **Miscellaneous**: Power BI, Debugging, Quality Assurance Mindset.
*   **Methodologies**: Agile, Scrum & Kanban, Problem Resolution Management, Technical Documentation.
*   **Certifications**: ISTQB Foundation.
*   **Languages**: Professional English and Spanish as mother language.

## Extracurricular Activity

**Machine Learning Student** | UAQ | Aug 2019 - Dec 2019
I took an elective course with students of the Master of Science in Artificial Intelligence, where we were looking at algorithms such as KNN, K-Means, random forest, among others, for wine classification and recognition of handwritten numbers.
